datalake:
  endpoint: localhost:9000
  bucket_name: raw
  folder_name: delta_lake
  access_key: ${MINIO_ROOT_USER}
  secret_key: ${MINIO_ROOT_PASSWORD}
  secure: false

dwh:
  host: localhost
  port: 5433
  database: ${POSTGRES_DB}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  staging_schema: staging
  production_schema: production
  stream_schema: stream

data:
  csv_path: ./data_local/raw
  delta_path: ./data_local/delta_format

spark:
  executor_memory: 8g

model:
  name: distilbert-base-uncased
  max_length: 512

stream:
  table: stream.raw_comments
  sleep_secs: 2
  kafka_bootstrap_servers: localhost:9092
  topic: toxic_comments.stream.raw_comments
