data_transformation:
  target: prod
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PG_HOST', 'localhost') }}"
      port: "{{ env_var('PG_PORT', '5432') | int }}"
      user: "{{ env_var('PG_USER') }}"
      pass: "{{ env_var('PG_PASSWORD') }}"
      database: "{{ env_var('PG_DB', 'k6') }}"
      schema: staging
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('PG_HOST', 'localhost') }}"
      port: "{{ env_var('PG_PORT', '5432') | int }}"
      user: "{{ env_var('PG_USER') }}"
      pass: "{{ env_var('PG_PASSWORD') }}"
      database: "{{ env_var('PG_DB', 'k6') }}"
      schema: production
      threads: 4